/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Service.BienTheService;
import Service.ImeiService;
import Service.SanPhamService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.BienThe;
import model.Imei;
import model.SanPham;

/**
 *
 * @author Quanglm
 */
public class tesst extends javax.swing.JFrame {

    private List<SanPham> lists = new ArrayList<>();
    private SanPhamService service = new SanPhamService();
    private DefaultTableModel model = new DefaultTableModel();
    private List<BienThe> lists1 = new ArrayList<>();
    private BienTheService service1 = new BienTheService();
    private DefaultTableModel model1 = new DefaultTableModel();
    private List<Imei> lists2 = new ArrayList<>();
    private ImeiService service2 = new ImeiService();
    private DefaultTableModel model2 = new DefaultTableModel();
    public tesst() {
        initComponents();
        lists = service.getAll();
        model = (DefaultTableModel) tblview.getModel();
        lists1 = service1.getAll1();
        model1 = (DefaultTableModel) tblview.getModel();
        lists2 = service2.getAll();
        model2 = (DefaultTableModel) tblview.getModel();
        showTable();
        showTableBT();
        
    }
    
    public void showTable(){
        model.setRowCount(0);
        for (SanPham sp : lists) {
            model.addRow(new Object[]{
                sp.getMaSanPham(),sp.getTenSanPham(),sp.getHeDieuHanh(),sp.getManHinh(),sp.getCanNang()
            });
        }
    }
    public void showTableBT(){
        model1.setRowCount(0);
        for (BienThe bt : lists1) {
            model1.addRow(new Object[]{
                bt.getMaBienThe(),bt.getMaSanPham(),bt.getMauSac(),bt.getCPU(),bt.getRam(),bt.getCard(),bt.getoCung(),bt.getGiaBan() + " VND"
            });
        }
    }
     public void showTableImei(){
        model2.setRowCount(0);
        for (Imei im : lists2) {
            model2.addRow(new Object[]{
                im.getMaBienThe(),im.getMaImei()
            });
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblview = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
            }
        ));
        jScrollPane1.setViewportView(tblview);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tesst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tesst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tesst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tesst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tesst().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblview;
    // End of variables declaration//GEN-END:variables
}
